### ISSUE TITLE
Deep combinator support

### ISSUE THREAD

**Issue by arose26** [filipeborelli/n8n-nodes-pptr-adv#1]
Just a few ideas. Puppeteer has support for navigating webpages containing a shadow DOM using either `pierce/<selector under shadow DOM>` or the convenient [deep combinator](https://pptr.dev/guides/page-interactions/#the--combinator-1) `>>>`.   
However, when attempting to use this n8n node to access a shadow DOM, I meet with difficulties.
`pierce/` seems to work in Page Wait for Selector operation, but I have yet to successfully Click or Hover a button under shadow DOM.
 `>>>`  never seems to work for any function. I'm not sure why this is, because node puppeteer should allow for it in `page.waitForSelector`. 
Also, it should be possible to use both syntaxes together as so: `pierce/.class1 >>> .deepchildclass`. 

***
**Okay, it seems this is purely a version issue. Upgrading puppeteer to puppeteer@20.3) allows for deep combinators in selector/click.**
One remaining problem is that the click's await stalls until timeout even though the click actually worked on the page. I'm currently looking into a fix for this.
***

Further notes:
`page.$eval(selector, function)` might be a better way of evaluating code that allows for evaluating on a specific puppeteer selector, since deep combinators can't be used in regular JS evaluations.

**Comment by filipeborelli** [comment]
Hello @arose26, thanks for your tips, I'll start applying them.
