### ISSUE TITLE
Page click with timeout

### ISSUE THREAD

**Issue by arose26** [filipeborelli/n8n-nodes-pptr-adv#2]
Currently, there are two issues which hinder page click with custom timeout.
1 - The `options` property is read as a string (even though in the code it's treated as IDataObject). This can be remedied by passing in an expression, e.g. {{ {timeout:1000} }}, however the code should probably convert a passed in JSON string to an object by default.
2 - in pageClick.ts, page.waitForNavigation() is called before page.click(selector, options). Since page.waitForNavigation takes no options, it will hang regardless. Either this should be disabled or waitForNavigation should also be called with options since it will also work with waitForNavigation( {timeout:1000} ).

**Comment by filipeborelli** [comment]
Hello @arose26 , thanks for your tips, I'll start applying them.

**Comment by arose26** [comment]
Hi @filipeborelli I have made a bunch of improvements on my local version, so what I can do is merge and then make a PR, if that is preferable :)

**Comment by filipeborelli** [comment]
@arose26 , you can open one PR with you changes?
Thank you!

**Comment by filipeborelli** [comment]
Resolved in the [pull request](https://github.com/filipeborelli/n8n-nodes-pptr-adv/pull/3)
